In [1]:
import pandas as pd

In [6]:
inventory = pd.read_csv('data/inventory.csv')

In [7]:
len(inventory)

460

In [8]:
sum(inventory["Count"])

552

In [9]:
inventory["Name"].to_csv('data/card_names.txt', index=False, header=False)

In [16]:
df = pd.read_csv('data/enriched_data.csv')

In [17]:
len(df)

457

In [18]:
df.head()

,toughness,color_identity,type_line,keywords,edhrec_rank,power,mana_cost,name,colors,rarity,cmc,oracle_text
0,1,['B'],Creature — Vampire Soldier,[],1753.0,1.0,{1}{B},Dusk Legion Zealot,['B'],common,2.0,When Dusk Legion Zealot enters the battlefield...
1,1,['W'],Creature — Insect,['Flying'],10790.0,0.0,{W},Goldenglow Moth,['W'],common,1.0,"Flying\nWhenever Goldenglow Moth blocks, you m..."
2,2,[],Artifact Creature — Scarecrow,[],3328.0,2.0,{3},Scuttlemutt,[],uncommon,3.0,{T}: Add one mana of any color.\n{T}: Target c...
3,1,['B'],Creature — Skeleton Warrior,[],637.0,1.0,{1}{B},Reassembling Skeleton,['B'],uncommon,2.0,{1}{B}: Return Reassembling Skeleton from your...
4,2,['R'],Creature — Goblin,[],8323.0,1.0,{3}{R},Mad Ratter,['R'],uncommon,4.0,"Whenever you draw your second card each turn, ..."

In [19]:
# Embereth appears twice since I have a foil and non-foil version of the card
inventory["Name"].value_counts()

Impassioned Orator                          2
Embereth Shieldbreaker // Battle Display    2
Emeria Angel                                2
Moorland Inquisitor                         2
Blossoming Sands                            2
                                           ..
Daybreak Chaplain                           1
Aspect of Lamprey                           1
Artificer's Assistant                       1
Hampering Snare                             1
Forbidden Alchemy                           1
Name: Name, Length: 455, dtype: int64

In [20]:
df.rarity.value_counts()

common      253
uncommon    149
rare         52
mythic        3
Name: rarity, dtype: int64

In [21]:
df.color_identity.value_counts()

['W']              121
['B']               98
['U']               86
[]                  39
['R']               34
['G']               30
['B', 'W']          18
['B', 'U']          10
['B', 'G']           6
['U', 'W']           3
['G', 'R']           3
['R', 'U']           3
['R', 'W']           2
['G', 'U']           2
['R', 'U', 'W']      1
['G', 'W']           1
Name: color_identity, dtype: int64

In [22]:
df.sort_values('edhrec_rank').head(5)

,toughness,color_identity,type_line,keywords,edhrec_rank,power,mana_cost,name,colors,rarity,cmc,oracle_text
315,NaN,[],Land,[],8.0,NaN,NaN,Evolving Wilds,[],common,0.0,"{T}, Sacrifice Evolving Wilds: Search your lib..."
207,NaN,['U'],Instant,[],56.0,NaN,{1}{U},Negate,['U'],common,2.0,Counter target noncreature spell.
287,1,['G'],Creature — Elf Shaman,[],58.0,2.0,{2}{G},Reclamation Sage,['G'],uncommon,3.0,"When Reclamation Sage enters the battlefield, ..."
150,4,['B'],Creature — Zombie,[],170.0,2.0,{3}{B}{B},Gray Merchant of Asphodel,['B'],uncommon,5.0,When Gray Merchant of Asphodel enters the batt...
55,NaN,['U'],Instant,[],206.0,NaN,{2}{U},Frantic Search,['U'],common,3.0,"Draw two cards, then discard two cards. Untap ..."

In [23]:
df.type_line.value_counts()

Instant                                            68
Sorcery                                            41
Enchantment                                        24
Enchantment — Aura                                 21
Artifact                                           15
                                                   ..
Creature — Vampire Cleric                           1
Legendary Creature — Human Wizard                   1
Creature — Elemental Lizard                         1
Creature — Giant Knight                             1
Creature — Human Soldier // Instant — Adventure     1
Name: type_line, Length: 155, dtype: int64

In [24]:
def classify_card_type(card):
    type_line = card["type_line"]
    if type_line.startswith("Instant"):
        return "Instant"
    if type_line.startswith("Sorcery"):
        return "Sorcery"
    if type_line.startswith("Land"):
        return "Land"
    if type_line == "Enchantment":
        return type_line
    if type_line == "Artifact":
        return type_line
    if type_line == "Legendary Artifact":
        return "Artifact"
    
    if "—" in type_line:
        
        if "Creature" in type_line:
            return "Creature"
        first, second = type_line.split("—")
        first = first.strip()
        second = second.strip()
        if first == "Legendary":
            return second
        if first == "Artifact":
            return first
        if first == "Basic Land":
            return "Land"
        if first == "Enchantment" and second == "Aura":
            return first
        if first == "Enchantment" and second == "Saga":
            return first

    return "Undefined"

df["card_type"] = df.apply(classify_card_type, axis=1)

In [25]:
df["card_type"].value_counts()

Creature       257
Instant         69
Enchantment     49
Sorcery         41
Artifact        28
Land            13
Name: card_type, dtype: int64

In [26]:
df.sort_values('cmc').tail(5)

,toughness,color_identity,type_line,keywords,edhrec_rank,power,mana_cost,name,colors,rarity,cmc,oracle_text,card_type
172,5,['B'],Creature — Specter // Sorcery — Adventure,[],12101.0,4.0,{5}{B}{B} // {3}{B},Reaper of Night // Harvest Fear,['B'],common,7.0,NaN,Creature
447,NaN,['W'],Sorcery,[],1848.0,NaN,{5}{W}{W},Mass Calcify,['W'],rare,7.0,Destroy all nonwhite creatures.,Sorcery
310,7,[],Artifact Creature — Wall,['Defender'],15136.0,5.0,{7},Roving Keep,[],common,7.0,Defender\n{7}: Roving Keep gets +2/+0 and gain...,Creature
211,4,"['B', 'W']",Creature — Giant Knight,['Afterlife'],9718.0,4.0,{5}{W}{B},Knight of the Last Breath,"['B', 'W']",uncommon,7.0,"{3}, Sacrifice another nontoken creature: Crea...",Creature
278,6,['U'],Creature — Giant,[],15080.0,5.0,{6}{U},Brine Giant,['U'],common,7.0,This spell costs {1} less to cast for each enc...,Creature

In [27]:
from ast import literal_eval

def classify_card_identity(card):
    l = literal_eval(card["color_identity"])
    identity = "|".join(l)
    identity = (identity.replace("W", "White")
    .replace("B", "Black")
    .replace("U", "Blue")
    .replace("G", "Green")
    .replace("R", "Red") )
    return identity if identity else "Colourless"


df["card_identity"] = df.apply(classify_card_identity, axis=1)

In [28]:
df["card_identity"].value_counts()

White             121
Black              98
Blue               86
Colourless         39
Red                34
Green              30
Black|White        18
Black|Blue         10
Black|Green         6
Red|Blue            3
Blue|White          3
Green|Red           3
Red|White           2
Green|Blue          2
Red|Blue|White      1
Green|White         1
Name: card_identity, dtype: int64

In [29]:
combined = df.set_index("name").join(inventory[["Name", "Count"]].set_index("Name"))

In [30]:
combined = combined.reset_index()
combined["name"] = combined["index"] # .reset_index()

In [31]:
del combined["index"]

In [32]:
combined.pivot_table(index="card_identity", columns="card_type", values="Count", aggfunc=sum) # .to_csv('manny.csv')

card_type       Artifact  Creature  Enchantment  Instant  Land  Sorcery
card_identity
Black                1.0      66.0         17.0     12.0   1.0     15.0
Black|Blue           NaN       8.0          NaN      2.0   4.0      NaN
Black|Green          NaN       4.0          1.0      1.0   NaN      NaN
Black|White          1.0      15.0          1.0      3.0   3.0      1.0
Blue                 1.0      54.0          9.0     25.0   1.0      7.0
Blue|White           NaN       1.0          NaN      1.0   1.0      NaN
Colourless          26.0      18.0          NaN      NaN   2.0      NaN
Green                NaN      16.0          1.0      8.0   NaN      5.0
Green|Blue           NaN       0.0          1.0      NaN   NaN      NaN
Green|Red            NaN       3.0          NaN      NaN   NaN      NaN
Green|White          NaN       NaN          NaN      NaN   2.0      NaN
Red                  NaN      23.0          4.0     11.0   2.0      7.0
Red|Blue             NaN       1.0          1.0      NaN   1.0      NaN
Red|Blue|White       NaN       NaN          NaN      NaN   NaN      1.0
Red|White            NaN       2.0          NaN      NaN   NaN      NaN
White                4.0      94.0         19.0     23.0   9.0     12.0

### Manual changes to the manny.csv file

In [148]:
df = pd.read_csv('manny.csv')

In [150]:
order = ["Black", "Blue", "Green", "Red", "White", "Colourless", "Black|Blue", "Black|Green", "Black|White", "Blue|White", "Green|Blue",
        "Green|Red", "Green|White", "Red|Blue", "Red|White", "Red|Blue|White"]
df['card_identity'] = pd.Categorical(df['card_identity'], order)
df.sort_values(by=["card_identity"])

     card_identity  Artifact  Creature  Enchantment  Instant  Land  Sorcery
0            Black         1        54           12        8     1       14
4             Blue         1        47            8       17     0        6
7            Green         0         0            1        3     0        2
11             Red         0        22            3       11     2        6
15           White         4        74           19       21     9        0
6       Colourless         0        15            0        0     3        0
1       Black|Blue         0         8            0        2     4        0
2      Black|Green         0         1            1        0     0        0
3      Black|White         0         4            1        0     1        0
5       Blue|White         0         1            0        1     1        0
8       Green|Blue         0         1            0        0     0        0
9        Green|Red         0         2            0        0     0        0
10     Green|White         0         0            0        0     1        0
12        Red|Blue         0         1            1        0     1        0
14       Red|White         0         2            0        0     0        0
13  Red|Blue|White         0         0            0        0     0        1